name: stockz
description: "Investment tracker"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: 3.3.1
  chopper: 7.1.1
  drift: 2.15.0
  encrypted_drift:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/encryption
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.9
  freezed_annotation: 2.4.1
  get_it: 7.6.7
  injectable: 2.3.2
  intl: 0.18.1
  json_annotation: 4.8.1
  json_serializable: 6.7.1
  logger: 2.0.2+1
  shared_preferences: 2.2.2
  url_launcher: 6.2.4

dev_dependencies:
  build_runner: 2.4.8
  chopper_generator: 7.1.1
  drift_dev: 2.15.0
  flutter_bloc: 8.1.3
  flutter_gen_runner: 5.4.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  injectable_generator: 2.4.1
  lint: 2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/config/
    - assets/test/
    - assets/test/offline_data/

flutter_gen:
  output: lib/core/assets
  line_length: 120
  assets:
    outputs:
      class_name: AppAssets
  # to generate run flutter pub run build_runner build -d -v

flutter_intl:
  main_locale: is
  enabled: true
  class_name: S
  arb_dir: lib/presentation/core/localization
  output_dir: lib/presentation/core/localization
  # to generate manually: dart run intl_utils:generate

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
