name: stockz
description: "Investment tracker"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  cached_network_image: 3.3.1
  chopper: 8.0.0
  drift: 2.18.0
  sqlite3_flutter_libs: 0.5.21
  sqflite: 2.3.3+1
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.10+1
  freezed_annotation: 2.4.1
  get_it: 7.7.0
  injectable: 2.4.1
  intl: 0.18.1
  json_annotation: 4.9.0
  json_serializable: 6.8.0
  logger: 2.3.0
  shared_preferences: 2.2.3
  syncfusion_flutter_charts: 25.2.4
  url_launcher: 6.2.6

dev_dependencies:
  build_runner: 2.4.9
  chopper_generator: 8.0.0
  drift_dev: 2.18.0
  flutter_bloc: 8.1.5
  flutter_gen_runner: 5.4.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  injectable_generator: 2.6.1
  lint: 2.3.0
  sqlite3_flutter_libs: 0.5.21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/config/
    - assets/test/
    - assets/test/offline_data/

flutter_gen:
  output: lib/core/assets
  line_length: 120
  assets:
    outputs:
      class_name: AppAssets

flutter_intl:
  main_locale: is
  enabled: true
  class_name: S
  arb_dir: lib/presentation/core/localization
  output_dir: lib/presentation/core/localization
